export const STUDENTS = [
    {
        id: 1,
        name: "Aarav Sharma",
        email: "aarav.sharma@example.com",
        phone: "9876543210",
        age: 20,
        gender: "Male",
        course: "Computer Engineering",
        year: 2,
        cgpa: 8.5,
        city: "Pune",
        status: "Active"
    },
    {
        id: 2,
        name: "Priya Patel",
        email: "priya.patel@example.com",
        phone: "9876543211",
        age: 21,
        gender: "Female",
        course: "Information Technology",
        year: 3,
        cgpa: 9.1,
        city: "Mumbai",
        status: "Active"
    },
    {
        id: 3,
        name: "Rohan Verma",
        email: "rohan.verma@example.com",
        phone: "9876543212",
        age: 19,
        gender: "Male",
        course: "Mechanical Engineering",
        year: 1,
        cgpa: 8.0,
        city: "Nashik",
        status: "Active"
    },
    {
        id: 4,
        name: "Sneha Joshi",
        email: "sneha.joshi@example.com",
        phone: "9876543213",
        age: 22,
        gender: "Female",
        course: "Electronics Engineering",
        year: 4,
        cgpa: 8.8,
        city: "Nagpur",
        status: "Placed"
    },
    {
        id: 5,
        name: "Aditya Kulkarni",
        email: "aditya.k@example.com",
        phone: "9876543214",
        age: 20,
        gender: "Male",
        course: "Computer Engineering",
        year: 2,
        cgpa: 7.9,
        city: "Kolhapur",
        status: "Active"
    },
    {
        id: 6,
        name: "Neha Singh",
        email: "neha.singh@example.com",
        phone: "9876543215",
        age: 21,
        gender: "Female",
        course: "Artificial Intelligence",
        year: 3,
        cgpa: 9.4,
        city: "Pune",
        status: "Active"
    },
    {
        id: 7,
        name: "Vikram Rao",
        email: "vikram.rao@example.com",
        phone: "9876543216",
        age: 22,
        gender: "Male",
        course: "Civil Engineering",
        year: 4,
        cgpa: 7.8,
        city: "Hyderabad",
        status: "Placed"
    },
    {
        id: 8,
        name: "Ananya Deshmukh",
        email: "ananya.d@example.com",
        phone: "9876543217",
        age: 20,
        gender: "Female",
        course: "Computer Engineering",
        year: 2,
        cgpa: 9.0,
        city: "Aurangabad",
        status: "Active"
    },
    {
        id: 9,
        name: "Rahul Gupta",
        email: "rahul.gupta@example.com",
        phone: "9876543218",
        age: 23,
        gender: "Male",
        course: "Electrical Engineering",
        year: 4,
        cgpa: 8.2,
        city: "Delhi",
        status: "Placed"
    },
    {
        id: 10,
        name: "Kavya Iyer",
        email: "kavya.iyer@example.com",
        phone: "9876543219",
        age: 19,
        gender: "Female",
        course: "Data Science",
        year: 1,
        cgpa: 9.3,
        city: "Chennai",
        status: "Active"
    },
    {
        id: 11,
        name: "Siddharth Jain",
        email: "siddharth.j@example.com",
        phone: "9876543220",
        age: 21,
        gender: "Male",
        course: "Cyber Security",
        year: 3,
        cgpa: 8.6,
        city: "Indore",
        status: "Intern"
    },
    {
        id: 12,
        name: "Meera Nair",
        email: "meera.nair@example.com",
        phone: "9876543221",
        age: 22,
        gender: "Female",
        course: "Computer Engineering",
        year: 4,
        cgpa: 9.2,
        city: "Kochi",
        status: "Placed"
    },
    {
        id: 13,
        name: "Arjun Mehta",
        email: "arjun.mehta@example.com",
        phone: "9876543222",
        age: 20,
        gender: "Male",
        course: "Information Technology",
        year: 2,
        cgpa: 8.1,
        city: "Ahmedabad",
        status: "Active"
    },
    {
        id: 14,
        name: "Pooja Yadav",
        email: "pooja.yadav@example.com",
        phone: "9876543223",
        age: 21,
        gender: "Female",
        course: "Computer Engineering",
        year: 3,
        cgpa: 8.7,
        city: "Lucknow",
        status: "Intern"
    },
    {
        id: 15,
        name: "Karan Malhotra",
        email: "karan.m@example.com",
        phone: "9876543224",
        age: 23,
        gender: "Male",
        course: "Mechanical Engineering",
        year: 4,
        cgpa: 7.7,
        city: "Jaipur",
        status: "Placed"
    },
    {
        id: 16,
        name: "Ishita Roy",
        email: "ishita.roy@example.com",
        phone: "9876543225",
        age: 20,
        gender: "Female",
        course: "AI & ML",
        year: 2,
        cgpa: 9.5,
        city: "Kolkata",
        status: "Active"
    },
    {
        id: 17,
        name: "Harsh Agrawal",
        email: "harsh.a@example.com",
        phone: "9876543226",
        age: 22,
        gender: "Male",
        course: "Computer Engineering",
        year: 4,
        cgpa: 8.3,
        city: "Bhopal",
        status: "Intern"
    },
    {
        id: 18,
        name: "Nisha Kapoor",
        email: "nisha.k@example.com",
        phone: "9876543227",
        age: 19,
        gender: "Female",
        course: "Information Technology",
        year: 1,
        cgpa: 8.9,
        city: "Chandigarh",
        status: "Active"
    },
    {
        id: 19,
        name: "Yash Patil",
        email: "yash.patil@example.com",
        phone: "9876543228",
        age: 21,
        gender: "Male",
        course: "Computer Engineering",
        year: 3,
        cgpa: 8.4,
        city: "Satara",
        status: "Active"
    },
    {
        id: 20,
        name: "Tanvi More",
        email: "tanvi.more@example.com",
        phone: "9876543229",
        age: 20,
        gender: "Female",
        course: "Electronics Engineering",
        year: 2,
        cgpa: 8.8,
        city: "Solapur",
        status: "Active"
    },
    {
        id: 21,
        name: "Omkar Jadhav",
        email: "omkar.j@example.com",
        phone: "9876543230",
        age: 22,
        gender: "Male",
        course: "Computer Engineering",
        year: 4,
        cgpa: 8.1,
        city: "Pune",
        status: "Placed"
    },
    {
        id: 22,
        name: "Riya Shah",
        email: "riya.shah@example.com",
        phone: "9876543231",
        age: 19,
        gender: "Female",
        course: "Data Science",
        year: 1,
        cgpa: 9.0,
        city: "Surat",
        status: "Active"
    },
    {
        id: 23,
        name: "Manav Bansal",
        email: "manav.b@example.com",
        phone: "9876543232",
        age: 21,
        gender: "Male",
        course: "Cyber Security",
        year: 3,
        cgpa: 8.5,
        city: "Noida",
        status: "Intern"
    },
    {
        id: 24,
        name: "Aditi Chavan",
        email: "aditi.chavan@example.com",
        phone: "9876543233",
        age: 22,
        gender: "Female",
        course: "Computer Engineering",
        year: 4,
        cgpa: 9.1,
        city: "Pune",
        status: "Placed"
    },
    {
        id: 25,
        name: "Devansh Mishra",
        email: "devansh.m@example.com",
        phone: "9876543234",
        age: 20,
        gender: "Male",
        course: "Artificial Intelligence",
        year: 2,
        cgpa: 8.7,
        city: "Kanpur",
        status: "Active"
    }
];